versions.properties

Upgrade kotest-assertions-core-jvm from + to 4.0.0

---

versions.properties

Upgrade logback-classic from 1.2.3 to 1.3.0-alpha5

---

versions.properties

Upgrade kotest-runner-junit5-jvm from + to 4.0.1

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.7.0 to 1.7.1

---

versions.properties

Upgrade ersion.kotlin from 1.3.70 to 1.3.71

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.7.1 to 1.7.2

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.7.2 to 1.7.3

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.7.3 to 1.7.4

---

versions.properties

Upgrade classgraph from 4.8.65 to 4.8.67

---

versions.properties

Upgrade detekt-formatting from 1.7.0 to 1.7.4

---

versions.properties

Upgrade classgraph from 4.8.67 to 4.8.68

---

versions.properties

Upgrade classgraph from 4.8.68 to 4.8.69

---

versions.properties

Upgrade classgraph from 4.8.69 to 4.8.70

---

versions.properties

Upgrade classgraph from 4.8.70 to 4.8.71

---

versions.properties

Upgrade classgraph from 4.8.71 to 4.8.72

---

versions.properties

Upgrade classgraph from 4.8.72 to 4.8.73

---

versions.properties

Upgrade classgraph from 4.8.73 to 4.8.75

---

versions.properties

Upgrade classgraph from 4.8.75 to 4.8.77

---

versions.properties

Upgrade classgraph from 4.8.77 to 4.8.78

---

versions.properties

Upgrade detekt-formatting from 1.8.0 to 1.9.0

---

versions.properties

Upgrade detekt-formatting from 1.9.0 to 1.9.1

---

versions.properties

Upgrade classgraph from 4.8.78 to 4.8.80

---

versions.properties

Upgrade classgraph from 4.8.80 to 4.8.81

---

versions.properties

Upgrade classgraph from 4.8.81 to 4.8.83

---

versions.properties

Upgrade classgraph from 4.8.83 to 4.8.84

---

versions.properties

Upgrade classgraph from 4.8.84 to 4.8.85

---

versions.properties

Upgrade classgraph from 4.8.85 to 4.8.86

---

build.gradle.kts
src/main/kotlin/org/danilopianini/upgradle/UpGradle.kt
src/main/kotlin/org/danilopianini/upgradle/api/Credentials.kt
src/main/kotlin/org/danilopianini/upgradle/config/Configurator.kt
src/main/kotlin/org/danilopianini/upgradle/modules/GradleRootModule.kt
src/main/kotlin/org/danilopianini/upgradle/modules/GradleWrapper.kt
src/main/kotlin/org/danilopianini/upgradle/modules/RefreshVersions.kt
src/main/kotlin/org/danilopianini/upgradle/remote/GraphqlSource.kt
src/test/kotlin/org/danilopianini/upgradle/config/TestAuthorConfig.kt
src/test/kotlin/org/danilopianini/upgradle/modules/TestRefreshVersions.kt
versions.properties

Upgrade ktlint from 9.2.1 to 9.3.0

---

versions.properties

Upgrade detekt from 1.10.0 to 1.11.0-RC1

---

versions.properties

Upgrade detekt from 1.11.0 to 1.11.1

---

versions.properties

Upgrade detekt from 1.11.1 to 1.11.2

---

versions.properties

Upgrade classgraph from 4.8.87 to 4.8.88

---

versions.properties

Upgrade classgraph from 4.8.88 to 4.8.89

---

versions.properties

Upgrade result from 3.0.1 to 3.1.0

---

versions.properties

Upgrade core from 5.8.0.202005061305-m2 to 5.9.0.202008260805-m3

---

src/main/kotlin/org/danilopianini/upgradle/modules/AbstractModule.kt
src/test/kotlin/org/danilopianini/upgradle/modules/TestStrategies.kt
versions.properties

Upgrade kotest from 4.2.2 to 4.2.3

---

versions.properties

Upgrade detekt-formatting from 1.12.0 to 1.13.1

---

versions.properties

Upgrade detekt-formatting from 1.13.1 to 1.14.0

---

build.gradle.kts
versions.properties

Upgrade fuel from 2.2.3 to 2.3.0

---

versions.properties

Upgrade kaml from 0.23.0 to 0.24.0

---

versions.properties

Upgrade shadow from 6.0.0 to 6.1.0

---

versions.properties

Upgrade kaml from 0.24.0 to 0.25.0

---

.github/workflows/build-external-pull-requests.yml

> Foreign pull request pipeline for Java 8 compatible Gradle projects
and this PR updates it to the same version of DanySK/centralized-automated-deployer@4e49517.
Hope it helps!

[Autodelivery] update Foreign pull request pipeline for Java 8 compatible Gradle projects from DanySK/centralized-automated-deployer@4e49517

---

.github/workflows/automerge.yml

> Automerge action
and this PR updates it to the same version of DanySK/centralized-automated-deployer@e7c5b5a.
Hope it helps!

[Autodelivery] update Automerge action from DanySK/centralized-automated-deployer@e7c5b5a

---

.github/workflows/build-and-deploy.yml

> Continuous Integration pipeline for Java 8 projects
and this PR updates it to the same version of DanySK/centralized-automated-deployer@6b8263b.
Hope it helps!

[Autodelivery] update Continuous Integration pipeline for Java 8 projects from DanySK/centralized-automated-deployer@6b8263b

---

.github/workflows/build-external-pull-requests.yml

> Foreign pull request pipeline for Java 8 projects
and this PR updates it to the same version of DanySK/centralized-automated-deployer@6b8263b.
Hope it helps!

[Autodelivery] update Foreign pull request pipeline for Java 8 projects from DanySK/centralized-automated-deployer@6b8263b

---

.github/workflows/build-and-deploy.yml

> Continuous Integration pipeline for Java 8 projects
and this PR updates it to the same version of DanySK/centralized-automated-deployer@89fb66c.
Hope it helps!

[Autodelivery] update Continuous Integration pipeline for Java 8 projects from DanySK/centralized-automated-deployer@89fb66c

---

.github/workflows/build-and-deploy.yml

> Continuous Integration pipeline for Java 8 projects
and this PR updates it to the same version of DanySK/centralized-automated-deployer@a33c351.
Hope it helps!

[Autodelivery] update Continuous Integration pipeline for Java 8 projects from DanySK/centralized-automated-deployer@a33c351

---

versions.properties

Upgrade kaml from 0.25.0 to 0.26.0

---

.github/workflows/automerge.yml

> Automerge action
and this PR updates it to the same version of DanySK/centralized-automated-deployer@e76ffbb.
Hope it helps!

[Autodelivery] update Automerge action from DanySK/centralized-automated-deployer@e76ffbb

---

src/main/kotlin/org/danilopianini/upgradle/UpGradle.kt
src/test/kotlin/org/danilopianini/upgradle/modules/TestRefreshVersions.kt
versions.properties

Upgrade kotlin from 1.4.10 to 1.4.20

---

versions.properties

Upgrade fuel from 2.3.0 to 2.3.1

---

versions.properties

Upgrade classgraph from 4.8.100 to 4.8.101

---

versions.properties

Upgrade classgraph from 4.8.101 to 4.8.102

---

versions.properties

Upgrade kaml from 0.26.0 to 0.27.0

---

src/main/kotlin/org/danilopianini/upgradle/modules/GradleWrapper.kt
versions.properties

Upgrade ktlint from 9.4.1 to 10.0.0

---

versions.properties

Upgrade kaml from 0.27.0 to 0.28.3

---

versions.properties

Upgrade kaml from 0.28.3 to 0.29.0

---

versions.properties

Upgrade kaml from 0.29.0 to 0.30.0

---

build.gradle.kts
src/main/kotlin/org/danilopianini/upgradle/api/Module.kt
src/main/kotlin/org/danilopianini/upgradle/modules/RefreshVersions.kt
versions.properties

Upgrade arrow-core from 0.12.0 to 0.13.1

---

versions.properties

Upgrade kaml from 0.30.0 to 0.31.0

---

versions.properties

Upgrade shadow from 6.1.0 to 7.0.0

---

versions.properties

Upgrade kaml from 0.31.0 to 0.34.0

---

versions.properties

Upgrade snakeyaml from 1.28 to 1.29

---

versions.properties

Upgrade kaml from 0.34.0 to 0.35.0
