DanySK/upgradle

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.0 to 4.0.1

---

versions.properties

Upgrade arrow-core from 0.10.4 to 0.10.5

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.1 to 4.0.2

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.1 to 4.0.2

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.2 to 4.0.3

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.2 to 4.0.3

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.3 to 4.0.4

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.3 to 4.0.4

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.4 to 4.0.5

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.4 to 4.0.5

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.8.0 to 1.9.0

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.9.0 to 1.9.1

---

src/main/kotlin/org/danilopianini/upgradle/Git.kt
src/main/kotlin/org/danilopianini/upgradle/UpGradle.kt
src/main/kotlin/org/danilopianini/upgradle/config/Configurator.kt
src/test/kotlin/TestAuthorConfig.kt

Fixes #61
Hey there!
Since the linked issue was stale for a while, I decided to pick it up. The default value for the email is what git recognizes as an 'empty' email.
Alternatively, I think not having a default would be better for this configuration, but that would require existing configs to update.

Make commit author configurable

---

README.md

Hi again, had a chance to test it now. Works as expected 🎉 
Is the documentation specific enough?
| No Config | Config |
| - | - |
| <img width="475" alt="No Config" src="https://user-images.githubusercontent.com/6658557/82578246-70e4f000-9b8c-11ea-857a-52ed5252f82c.png"> | <img width="316" alt="image" src="https://user-images.githubusercontent.com/6658557/82578366-92de7280-9b8c-11ea-888c-daf190f1e739.png"> |

Document usage of the 'author' config

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.5 to 4.0.6

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.5 to 4.0.6

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.9.1 to 1.10.0-RC1

---

versions.properties

Upgrade com.github.johnrengelman.shadow from 5.2.0 to 6.0.0

---

versions.properties

Upgrade kotest-runner-junit5 from 4.0.6 to 4.1.0.RC2

---

versions.properties

Upgrade kotest-assertions-core-jvm from 4.0.6 to 4.1.0.RC2

---

versions.properties

Upgrade detekt-formatting from 1.9.1 to 1.10.0-RC1

---

versions.properties

Upgrade kotest from 4.1.0.RC2 to 4.1.0

---

versions.properties

Upgrade io.gitlab.arturbosch.detekt from 1.10.0-RC1 to 1.10.0

---

versions.properties

Upgrade detekt-formatting from 1.10.0-RC1 to 1.10.0

---

versions.properties

Upgrade detekt from 1.11.0-RC1 to 1.11.0-RC2

---

versions.properties

Upgrade detekt from 1.11.0-RC2 to 1.11.0

---

versions.properties

Upgrade mockito-core from 3.5.2 to 3.5.5

---

build.gradle.kts
versions.properties

Upgrade dokka from 0.10.1 to 1.4.0-rc

---

versions.properties

Upgrade detekt-formatting from 1.12.0-RC1 to 1.12.0

---

versions.properties

Upgrade arrow-core from 0.10.5 to 0.11.0

---

versions.properties

Upgrade commons-io from 2.7 to 2.8.0

---

versions.properties

Upgrade commons-io from 2.8.0 to 20030203.000550

---

versions.properties

Upgrade commons-io from 2.6 to 2.7

---

versions.properties

Upgrade detekt-formatting from 1.14.2 to 1.15.0

---

versions.properties

Upgrade snakeyaml from 1.27 to 1.28

---

versions.properties

Upgrade arrow-core from 0.11.0 to 0.12.0

---

versions.properties

Upgrade gradle-tooling-api from 6.8.3 to 7.0

---

versions.properties

Upgrade gradle-tooling-api from 7.0 to 7.0.1

---

versions.properties

Upgrade gradle-tooling-api from 7.0.1 to 7.0.2

---

versions.properties

Upgrade kotlin from 1.4.32 to 1.5.10

---

versions.properties

Upgrade gradle-tooling-api from 7.0.2 to 7.1

---

versions.properties

Upgrade commons-io from 2.10.0 to 20030203.000550

---

versions.properties

Upgrade gradle-tooling-api from 7.1 to 7.1.1
